# Generated by Django 5.1.4 on 2024-12-15 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nomi')),
                ('country', models.CharField(max_length=50, verbose_name='Shaxri')),
            ],
            options={
                'verbose_name': 'Brend ',
                'verbose_name_plural': 'Brendlar',
            },
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=150, unique=True, verbose_name='modellar')),
                ('description', models.TextField(verbose_name='Tasviri')),
                ('year', models.IntegerField(verbose_name='Yili')),
                ('color', models.CharField(max_length=50, verbose_name='rangi')),
                ('price', models.IntegerField(verbose_name='Narxi')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.brand', verbose_name='Brendi')),
            ],
            options={
                'verbose_name': 'Moshina',
                'verbose_name_plural': 'Moshinalar',
                'ordering': ['-id'],
            },
        ),
    ]
